# Two pods, one container each
# Each container asking for 1 distinct Fake

---
apiVersion: v1
kind: Namespace
metadata:
  name: test1

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: test1
  name: default-fake-template
spec:
  spec:
    resourceClassName: fake.3-shake.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: test1
  name: pod0
  labels:
    app: pod0
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - name: ctr0
    image: cgr.dev/chainguard/wolfi-base:latest
    command: ["ash", "-c"]
    args: ["export; sleep infinity"]
    resources:
      claims:
      - name: distinct-fake
  - name: ctr1
    image: cgr.dev/chainguard/wolfi-base:latest
    command: ["ash", "-c"]
    args: ["export; sleep infinity"]
    resources:
      claims:
      - name: distinct-fake
  resourceClaims:
  - name: distinct-fake
    source:
      resourceClaimTemplateName: default-fake-template

---
apiVersion: v1
kind: Pod
metadata:
  namespace: test1
  name: pod1
  labels:
    app: pod1
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - name: ctr0
    image: cgr.dev/chainguard/wolfi-base:latest
    command: ["ash", "-c"]
    args: ["export; sleep infinity"]
    resources:
      claims:
      - name: distinct-fake
  resourceClaims:
  - name: distinct-fake
    source:
      resourceClaimTemplateName: default-fake-template
